version: "3.8"

services:
  matchmaking_redis_table:
    image: redis:latest
    container_name: redis_instance_1
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - redis_data_1:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  games_redis_table:
    image: redis:latest
    container_name: redis_instance_2
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - redis_data_2:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data_1:
  redis_data_2:
